# Generated by Django 2.0.12 on 2019-07-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0003_remove_supportingmember_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bikes',
            field=models.IntegerField(help_text='How many bikes are we talking about?', null=True),
        ),
    ]
