version: "3"

services:
  web:
    build: .
    command: sh -c "gunicorn rw.wsgi:application --bind 0.0.0.0:8000"
    container_name: rueckenwind_app
    expose:
      - 8000
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
