# Generated by Django 2.0.5 on 2018-06-15 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikedonation',
            old_name='bikes',
            new_name='bike_count',
        ),
    ]
