# Generated by Django 2.0.5 on 2018-06-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fff', '0003_auto_20180618_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikedonation',
            name='latitude',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='bikedonation',
            name='longitude',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
