# Generated by Django 2.0.12 on 2019-07-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fff', '0004_auto_20190727_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(choices=[('NOREASON', 'No reason'), ('TOOLONG', 'Too long'), ('OTHERBIKE', 'Other bike')], default='NOREASON', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(blank=True, help_text='Date at which the order was placed', null=True),
        ),
    ]
