# Generated by Django 2.0.5 on 2018-06-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fff', '0004_auto_20180619_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikedonation',
            name='bike_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikedonation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bikedonation',
            name='latest_pickup',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bikedonation',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bikedonation',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
