# Generated by Django 2.0.5 on 2018-06-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fff', '0005_auto_20180620_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikedonation',
            name='latitude',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='bikedonation',
            name='longitude',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
