# Generated by Django 2.0.6 on 2019-03-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fff', '0006_auto_20180620_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
