# Generated by Django 2.0.6 on 2019-04-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fff', '0010_auto_20190403_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
