# Generated by Django 2.0.6 on 2019-07-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fff', '0011_auto_20190403_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_input',
            new_name='date_ordered',
        ),
    ]
