# Generated by Django 2.0.6 on 2019-07-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fff', '0012_auto_20190705_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
